# Generated by Django 6.0.4 on 2026-04-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0006_incident_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomadminprofile',
            options={'verbose_name': 'Hồ sơ Quản trị phòng', 'verbose_name_plural': 'Hồ sơ Quản trị phòng'},
        ),
        migrations.AlterField(
            model_name='incident',
            name='is_markdown',
            field=models.BooleanField(default=False, help_text='Bật khi nội dung được soạn bằng trình Markdown mở rộng; tắt với tin nhắn một dòng nhanh, khi đó văn bản sẽ được hiển thị dạng thuần (chỉ xử lý SBD được nhắc).'),
        ),
        migrations.AlterField(
            model_name='incidentparticipant',
            name='relation_type',
            field=models.CharField(choices=[('reported', 'Đối tượng chính'), ('mentioned', 'Được nhắc')], max_length=20),
        ),
    ]
